openapi: 3.0.3
info:
  title: papiNet API
  description: papinet API is a global initiative for the Forst and Paper supply chain.
  contact:
    name: papiNet API CWG
    url: https://github.com/papinet/papiNet-API/issues
  license:
    name: Apache 2.0
    url: https://github.com/papinet/papiNet-API/blob/patrice-v1.0.0/LICENSE
  version: 1.0.0
servers:
  - url: https://papinet.papinet.io
    description: papiNet Mock Server
paths:

  '/orders':
    # get /orders
    get:
      summary: List `orders`
      description: Gets a paginated list of all `orders`.
      parameters:
        - in: query
          name: orderStatus
          description: Filter by status
          required: false
          schema:
            type: string
            enum:
            - Active
            - Cancelled
            - Completed
        - in: query
          name: offset
          description: The number of items to skip before starting to collect the result set.
          required: false
          schema:
            type: string
        - in: query
          name: limit
          description: The maximum number of items to return. If the value exceeds the maximum, then the maximum value will be used.
          required: false
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfOrders'

  '/orders/{orderId}':
    # get /orders/{orderId}
    get:
      summary: Get an `order`
      description: Gets the details of a specific `order`, including a paginated list of all its lines.
      parameters:
        - in: path
          name: orderId
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of the `order` to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetOrder'

components:
  schemas:

    PaginationLinks:
      type: object
      required:
        - next
      properties:
        first:
          type: object
          properties:
            href:
              type: string
        prev:
          type: object
          properties:
            href:
              type: string
        next:
          type: object
          properties:
            href:
              type: string
        last:
          type: object
          properties:
            href:
              type: string

    ListOfOrders:
      type: object
      properties:
        orders:
          type: array
          items:
            $ref: '#/components/schemas/OrderHeader'
        links:
          $ref: '#/components/schemas/PaginationLinks'

    GetOrder:
      $ref: '#/components/schemas/Order'

    OrderHeader:
      type: object
      required:
        - id
        - orderNumber
        - orderStatus
        - numberOfLineItems
      properties:
        id:
          type: string
          format: uuid
        orderNumber:
          type: string
        orderStatus:
          type: string
          # Enumeration for 'orderStatus':
          enum:
            - Active
            - Cancelled
            - Completed
        numberOfLineItems:
          type: integer
          minimum: 0
    OrderLineItem:
      type: object
      required:
        - id
        - orderLineItemNumber
        - orderLineItemStatus
      properties:
        id:
          type: string
          format: uuid
        orderLineItemNumber:
          type: integer
          minimum: 0
        orderLineItemStatus:
          type: string
          # Enumeration for 'orderLineItemStatus':
          enum:
            - Cancelled
            - Completed
            - Confirmed
            - Pending
            - ProductionCompleted
            - ShipmentCompleted
        changeable:
          type: boolean
        quantities:
          type: array
          items:
            type: object
            properties:
              quantityContext:
                type: string
                # Enumeration for 'quantityContext':
                enum:
                  - Confirmed
                  - Invoiced
                  - Ordered
                  - Produced
                  - Shipped
              quantityType:
                type: string
                # Enumeration for 'quantityType':
                enum:
                  - Area
                  - Count
                  - GrossWeight
                  - Length
                  - NetNetWeight
                  - NetWeight
                  - NominalWeight
                  - TareWeight
              quantityValue:
                type: number
              quantityUOM:
                type: string
                # Enumeration for 'quantityUOM':
                enum:
                  - Bale
                  - Box
                  - Centimeter
                  - Decimeter
                  - Foot
                  - Gram
                  - HundredPounds
                  - Inch
                  - Kilogram
                  - Kilometer
                  - Meter
                  - MetricTon
                  - Millimeter
                  - Package
                  - PalletUnit
                  - Piece
                  - Pound
                  - PulpUnit
                  - Ream
                  - Reel
                  - Sheet
                  - ShortTon
                  - Skid
                  - SquareDecimeter
                  - SquareFoot
                  - SquareInch
                  - SquareMeter
                  - ThousandPieces
                  - ThousandSquareCentimeters
                  - ThousandSquareFeet
                  - ThousandSquareInches
                  - Yard

    Order:
      allOf:
        - $ref: '#/components/schemas/OrderHeader'
        - properties:
            orderLineItems:
              type: array
              items:
                $ref: '#/components/schemas/OrderLineItem'
            links:
              $ref: '#/components/schemas/PaginationLinks'
