openapi: 3.1.0
info:
  title: papiNet API
  description: papinet API is a global initiative for the Forest and Paper supply chain.
  contact:
    name: papiNet API CWG
    url: https://github.com/papinet/papiNet-API/issues
  license:
    name: Apache 2.0
    url: https://github.com/papinet/papiNet-API/blob/master/LICENSE
  version: 3.0.0
servers:
  - url: http://localhost:3020
    description: papiNet Mock Server
paths:

  ## DELIVERY NOTE (2)

  '/delivery-notes':
    # GET /delivery-notes
    # None => ListOfDeliveryNotes
    get:
      summary: List `delivery-notes`
      description: Get a paginated list of all `delivery-notes`.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfDeliveryNotes'
        '204':
          description: No Content

  '/delivery-notes/{deliveryNoteId}':
    # GET /delivery-notes/{deliveryNoteId}
    # None => GetDeliveryNoteById
    get:
      summary: Get a `delivery-note`
      description: Gets the details of a specific `delivery-note`.
      parameters:
        - in: path
          name: deliveryNoteId
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of the `delivery-note` to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetDeliveryNoteById'
        '404':
          description: Not Found

components:
  schemas:

    # Re-usable schema(s):

    PaginationLinks:
      type: object
      # none of the properties are required.
      properties:
        first:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference
        prev:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference
        next:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference
        last:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference

    # 'Big' structure schema(s):

    Paper:
      type: object
      properties:
        # Properties that do not depend on the reel or sheet format:
        coatingTop:
          type: string
          enum:
            - Acrylic
            - Flexolyn
            - FoilCoated
            - GreaseBarrier
            - Metallic
            - MetalizedPolyester
            - MoistureBarrier
            - MoldInhibitor
            - None
            - OilBarrier
            - OxygenBarrier
            - Plastic
            - PolyCoating
            - Polyethylene
            - Pyroxylin
            - Silicone
        coatingBottom:
          type: string
          enum:
            - Acrylic
            - Flexolyn
            - FoilCoated
            - GreaseBarrier
            - Metallic
            - MetalizedPolyester
            - MoistureBarrier
            - MoldInhibitor
            - None
            - OilBarrier
            - OxygenBarrier
            - Plastic
            - PolyCoating
            - Polyethylene
            - Pyroxylin
            - Silicone
        finishType:
          type: string
          enum:
            - Dull
            - English
            - Gloss
            - Laid
            - Linen
            - Machine
            - Matte
            - Satin
            - SCA
            - SCB
            - SCC
            - Silk
            - Smooth
            - SoftGloss
            - Vellum
            - Velvet
        printType:
          type: string
          enum:
            - ColdsetOffset
            - ContinuousForms
            - Digital
            - Flexography
            - FoilPrint
            - Forms
            - Gravure
            - HeatsetOffset
            - InkJet
            - InstantOffset
            - Laser
            - Letterpress
            - LightPrint
            - MiniWeb
            - RotoFlexography
            - RotoGravure
            - RotoLetterpress
            - RotoSilkScreen
            - SheetfedOffset
            - SilkScreen
            - WebOffset
        basisWeight: # This is the result of a nice compromise between EU and US usage.
          type: object
          required:
            - value
            - uom
          properties:
            sizeType:
              type: string
              enum:
                - 24x36
                - 25x38
            value:
              type: number
              exclusiveMinimum: 0
            uom:
              type: string
              enum:
                - GramsPerSquareMeter
                - Pound
        bulk:
          type: object
          required:
            - value
            - uom
          properties:
            value:
              type: number
              exclusiveMinimum: 0
            uom:
              type: string
              enum:
                - CubicCentimeterPerGram
        caliper:
          type: object
          required:
            - value
            - uom
          properties:
            value:
              type: number
              exclusiveMinimum: 0
            uom:
              type: string
              enum:
                - Micron
                - Millimeter
        colourShade:
          type: object
          required:
            - value
            - assignedBy
          properties:
            value:
              type: string
              minLength: 1
            assignedBy:
              type: string
              enum:
                - Buyer
                - Customer
                - EndUser
                - Seller
                - Supplier
        colourDescription:
          type: string
          minLength: 1
        recycledContent:
          type: object
          required:
            - value
            - uom
          properties:
            value:
              type: number
              minimum: 0
              maximum: 100
            uom:
              type: string
              enum:
                - Percentage
        format:
          type: string
          enum:
            - Reel
            - Sheet
        # Properties that are common to reel or sheet format:
        width:
          type: object
          required:
            - value
            - uom
          properties:
            value:
              type: number
              exclusiveMinimum: 0
            uom:
              type: string
              enum:
                - Centimeter
                - Inch
                - Millimeter
        length:
          type: object
          required:
            - value
            - uom
          properties:
            value:
              type: number
              exclusiveMinimum: 0
            uom:
              type: string
              enum:
                - Centimeter
                - Foot
                - Inch
                - Meter
                - Millimeter
                - Yard
        # Properties that are specific to reel format:
        windingDirection:
          type: string
          enum:
            - WireSideIn
            - WireSideOut
        reelMakeToConstraint:
          type: string
          enum:
            - Length
            - Diameter
        reelDiameter:
          type: object
          required:
            - value
            - uom
          properties:
            value:
              type: number
              exclusiveMinimum: 0
            uom:
              type: string
              enum:
                - Centimeter
                - Inch
                - Millimeter
        coreEndType:
          type: string
          enum:
            - Adaptor
            - Bevelled
            - Bridge
            - Notched
            - NotchedFullMetal
            - Plain
            - PlainFullMetal
            - Tapered
        coreMaterialType:
          type: string
          enum:
            - Aluminium
            - Composite
            - Fibre
            - Iron
            - Paper
            - Plastic
            - Steel
        coreDiameterInside:
          type: object
          required:
            - value
            - uom
          properties:
            value:
              type: number
              exclusiveMinimum: 0
            uom:
              type: string
              enum:
                - Centimeter
                - Inch
                - Millimeter
        coreStrengthCode:
          type: object
          required:
            - value
            - assignedBy
          properties:
            value:
              type: string
              minLength: 1
            assignedBy:
              type: string
              enum:
                - Buyer
                - Customer
                - EndUser
                - Seller
                - Supplier
        # Properties that are specific to sheet format:
        grainDirection:
          type: string
          enum:
            - Long
            - Short

    Pulp:
      type: object # This is just a placeholder for now.

    # API endpoint schemas:

    ListOfDeliveryNotes:
      type: object
      required:
        - deliveryNoteCount
        - deliveryNotes
        # links is not required
      properties:
        deliveryNoteCount:
          type: integer
          minimum: 1
        deliveryNotes:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - id
              - deliveryNoteNumber
              - deliveryNoteTimestamp
              - deliveryNoteStatus
              - shipmentStatus
              # transport is not required
              # carrierParty is not required
              - shipFromLocation
              - shipToLocation
              - LineItemCount
            properties:
              id:
                type: string
                format: uuid
              deliveryNoteNumber:
                type: string
                minLength: 1
              deliveryNoteTimestamp:
                type: string
                format: date-time # UTC MUST be used!
              deliveryNoteStatus:
                type: string
                enum:
                  - Original
                  - Replaced
                  - Cancelled
              shipmentStatus:
                type : string
                enum:
                  - Planned
                  - Departed
                  - Arrived
              transport:
                type: object
                required:
                  - modeType
                  # unitType is not required
                properties:
                  modeType:
                    type: string
                    enum:
                      - InlandWaterway
                      - Intermodal
                      - Multimodal
                      - Rail
                      - Road
                      - Sea
                  unitType:
                    type: string
                    enum:
                      - Barge
                      - Cassette
                      - Container
                      - DrawBarCombination
                      - RailCar
                      - RigidLorry
                      - Trailer
                      - VesselUnit
              carrierParty:
                type: object
                required:
                  # id is not required
                  # partyIdentifiers is not required
                properties:
                  id:
                    type: string
                    format: uuid
                  partyIdentifiers:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      required:
                        - value
                        - assignedBy
                      properties:
                        value:
                          type: string
                          minLength: 1
                        assignedBy:
                          type: string
                          enum:
                            - Supplier
              shipFromLocation:
                type: object
                required:
                  # id is not required
                  # locationIdentifiers is not required
                properties:
                  id:
                    type: string
                    format: uuid
                  locationIdentifiers:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      required:
                        - value
                        - assignedBy
                      properties:
                        value:
                          type: string
                          minLength: 1
                        assignedBy:
                          type: string
                          enum:
                            - Supplier
              shipToLocation:
                type: object
                required:
                  # id is not required
                  # locationIdentifiers is not required
                properties:
                  id:
                    type: string
                    format: uuid
                  locationIdentifiers:
                    type: array
                    minItems: 1
                    items:
                      type: object
                      required:
                        - value
                        - assignedBy
                      properties:
                        value:
                          type: string
                          minLength: 1
                        assignedBy:
                          type: string
                          enum:
                            - Supplier
              LineItemCount:
                type: integer
                minimum: 1
        links:
          $ref: '#/components/schemas/PaginationLinks'

    GetDeliveryNoteById: {}