openapi: 3.1.0
info:
  title: papiNet API
  description: papinet API is a global initiative for the Forest and Paper supply chain.
  contact:
    name: papiNet API CWG
    url: https://github.com/papinet/papiNet-API/issues
  license:
    name: Apache 2.0
    url: https://github.com/papinet/papiNet-API/blob/master/LICENSE
  version: 3.0.0
servers:
  - url: http://localhost:3020
    description: papiNet Mock Server
paths:

  ## SUPPLIER ORDER (2)

  '/supplier-orders':
    # GET /supplier-orders
    # None => ListOfSupplierOrders
    get:
      summary: List `supplier-orders`
      description: Get a paginated list of all `supplier-orders`.
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListOfSupplierOrders'
        '204':
          description: No Content

  '/supplier-orders/{supplierOrderId}':
    # GET /supplier-orders/{supplierOrderId}
    # None => GetSupplierOrderById
    get:
      summary: Get a `supplier-order`
      description: Gets the details of a specific `supplier-order`.
      parameters:
        - in: path
          name: supplierOrderId
          schema:
            type: string
            format: uuid
          required: true
          description: UUID of the `supplier-order` to get
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/GetSupplierOrderById'
        '404':
          description: Not Found

components:
  schemas:

    # Re-usable schema(s):

    PaginationLinks:
      type: object
      # none of the properties are required.
      properties:
        first:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference
        prev:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference
        next:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference
        last:
          type: object
          required:
            - href
          properties:
            href:
              type: string
              format: uri-reference

    # 'Big' structure schema(s):

    Paper:
      type: object
      properties:
        # Properties that do not depend on the reel or sheet format:
        coatingTop:
          type: string
          enum:
            - Acrylic
            - Flexolyn
            - FoilCoated
            - GreaseBarrier
            - Metallic
            - MetalizedPolyester
            - MoistureBarrier
            - MoldInhibitor
            - None
            - OilBarrier
            - OxygenBarrier
            - Plastic
            - PolyCoating
            - Polyethylene
            - Pyroxylin
            - Silicone
        coatingBottom:
          type: string
          enum:
            - Acrylic
            - Flexolyn
            - FoilCoated
            - GreaseBarrier
            - Metallic
            - MetalizedPolyester
            - MoistureBarrier
            - MoldInhibitor
            - None
            - OilBarrier
            - OxygenBarrier
            - Plastic
            - PolyCoating
            - Polyethylene
            - Pyroxylin
            - Silicone
        finishType:
          type: string
          enum:
            - Dull
            - English
            - Gloss
            - Laid
            - Linen
            - Machine
            - Matte
            - Satin
            - SCA
            - SCB
            - SCC
            - Silk
            - Smooth
            - SoftGloss
            - Vellum
            - Velvet
        printType:
          type: string
          enum:
            - ColdsetOffset
            - ContinuousForms
            - Digital
            - Flexography
            - FoilPrint
            - Forms
            - Gravure
            - HeatsetOffset
            - InkJet
            - InstantOffset
            - Laser
            - Letterpress
            - LightPrint
            - MiniWeb
            - RotoFlexography
            - RotoGravure
            - RotoLetterpress
            - RotoSilkScreen
            - SheetfedOffset
            - SilkScreen
            - WebOffset
        basisWeight: # This is the result of a nice compromise between EU and US usage.
          type: object
          required:
            - value
            - UOM
          properties:
            sizeType:
              type: string
              enum:
                - 24x36
                - 25x38
            value:
              type: number
              minimum: 0
            UOM:
              type: string
              enum:
                - GramsPerSquareMeter
                - Pound
        bulk:
          type: object
          required:
            - value
            - UOM
          properties:
            value:
              type: number
            UOM:
              type: string
              enum:
                - CubicCentimeterPerGram
        caliper:
          type: object
          required:
            - value
            - UOM
          properties:
            value:
              type: number
            UOM:
              type: string
              enum:
                - Micron
                - Millimeter
        colourShade:
          type: object
          required:
            - value
            - agency
          properties:
            value:
              type: string
              minLength: 1
            agency:
              type: string
              enum:
                - Buyer
                - Customer
                - EndUser
                - Seller
                - Supplier
        colourDescriptions:
          type: array
          minItems: 1
          items:
            type: string
            minLength: 1
        recycled:
          type: array
          minItems: 1
          items:
            type: object
            required:
              - value
              - UOM
            properties:
              value:
                type: number
              UOM:
                type: string
                enum:
                  - Percentage
        format:
          type: string
          enum:
            - Reel
            - Sheet
        # Properties that are common to reel or sheet format:
        width:
          type: object
          required:
            - value
            - UOM
          properties:
            value:
              type: number
            UOM:
              type: string
              enum:
                - Centimeter
                - Inch
                - Millimeter
        length:
          type: object
          required:
            - value
            - UOM
          properties:
            value:
              type: number
            UOM:
              type: string
              enum:
                - Centimeter
                - Foot
                - Inch
                - Meter
                - Millimeter
                - Yard
        # Properties that are specific to reel format:
        windingDirection:
          type: string
          enum:
            - WireSideIn
            - WireSideOut
        reelMakeToConstraint:
          type: string
          enum:
            - Length
            - Diameter
        reelDiameter:
          type: object
          required:
            - value
            - UOM
          properties:
            value:
              type: number
            UOM:
              type: string
              enum:
                - Centimeter
                - Inch
                - Millimeter
        coreEndType:
          type: string
          enum:
            - Adaptor
            - Bevelled
            - Bridge
            - Notched
            - NotchedFullMetal
            - Plain
            - PlainFullMetal
            - Tapered
        coreMaterialType:
          type: string
          enum:
            - Aluminium
            - Composite
            - Fibre
            - Iron
            - Paper
            - Plastic
            - Steel
        coreDiameterInside:
          type: object
          required:
            - value
            - UOM
          properties:
            value:
              type: number
            UOM:
              type: string
              enum:
                - Centimeter
                - Inch
                - Millimeter
        coreStrengthCode:
          type: object
          required:
            - value
            - agency
          properties:
            value:
              type: string
              minLength: 1
            agency:
              type: string
              enum:
                - Buyer
                - Customer
                - EndUser
                - Seller
                - Supplier
        # Properties that are specific to sheet format:
        grainDirection:
          type: string
          enum:
            - Long
            - Short

    Pulp:
      type: object # This is just a placeholder for now.

    # API endpoint schemas:

    ListOfSupplierOrders: {}

    GetSupplierOrderById:
      type: object
      properties:
        id:
          type: string
          format: uuid
        supplierOrderNumber:
          type: string
          minLength: 1
        supplierOrderTimestamp:
          type: string
          format: date-time # UTC MUST be used!
        supplierOrderStatus:
          type: string
          enum:
            - Original
            - Amended
            - Cancelled
        active:
          type: boolean
        supplierParty: